### ISSUE TITLE
Is there a specific reason not to run controller on pi instead of Nano?

### ISSUE THREAD

**Issue by ex3ndr** [Improbable-AI/walk-these-ways#31]
Hi! I am trying to figure out how you made this and a little bit puzzled by the need to run locomotion on one of the nanos. Why is that?

**Comment by gmargo11** [comment]
Hi @ex3ndr ,

I'm pretty sure it's possible to run our controller from the Pi. You'll just need to install Pytorch and LCM, or rebuild the docker image from a compatible base image. I set up this deployment environment on the Nano because of some other requirements in my research. Specifically, I want to use the camera images for some other tasks, and the cameras on Go1 are connected to the Nano. 

-Gabe
