### ISSUE TITLE
When deployed, Go1 still moves despite neutral commands are given

### ISSUE THREAD

**Issue by breakds** [Improbable-AI/walk-these-ways#43]
Hi Gabe,

I was able to deploy the provided checkpoint on the Go1 EDU. Under neutral commands, i.e. when the 15 individual commands are

```python
cmd_x = 0
cmd_y = 0
cmd_yaw = 0 
cmd_height = 0
cmd_freq = 3.0
# Mode = 1
cmd_phase = 0.5
cmd_offset = 0.0
cmd_bound = 0.0
cmd_duration = 0.5
cmd_footswing = 0.08
cmd_ori_pitch = 0.0
cmd_ori_roll = 0.0
cmd_stance_width = 0.33
cmd_stance_length = 0.4
cmd_aux_reward = 0.0
```

I expect the robot to stay where it is (with feet lifting and dropping). However there was a positive `v_x` and nonzero `v_y` observed so that the robot is actually walking towards front-right. Is this because I misunderstood some of the command above? 

Thanks a lot!

**Comment by gmargo11** [comment]
Hi @breakds,

Yes, I've noticed the same thing. There are a few ways to fix it; I think many production-quality systems add at least one of these:

- If the drift is constant, tune a small constant velocity correction that corrects it and always add this to the command.
- Make the robot stand still with all four feet on the ground when the command is small enough. If the robot is standing instead of trotting, it's much easier not to drift.
- Implement a velocity estimator that uses either the IMU or the optical flow from a camera. Then use this to compute a velocity correction based on the error from the commanded velocity.

-Gabe
