### ISSUE TITLE
deployment_image.tar file is too small(2.4kB)

### ISSUE THREAD

**Issue by dongjukim123** [Improbable-AI/walk-these-ways#70]
When I commanded send_to_unitree.sh in go1_gym_deploy/scripts file I got a very small file size 2.4kB deployment_image.tar 
Is it right? You said that is is 3.5GB size but mine is too small.
And when I executed install_deployment_code.sh in the scripts file I got an error like this one(Invalid tar header)
![Screenshot from 2024-03-06 14-36-43](https://github.com/Improbable-AI/walk-these-ways/assets/122246838/146ea83d-386f-4674-9fc1-ccb30e4c05c9)

**Comment by amanarora9848** [comment]
Hi @dongjukim123

The file you downloaded is most likely corrupted. The solution has been mentioned on this [issue](https://github.com/Improbable-AI/walk-these-ways/issues/42#issuecomment-1623976517).

I think the reason is that the file as you know is too large (3.5GB), is because the file is stored in google drive and the `wget` command in the script has to handle the confirmation token for downloading this large file, which is where the error might be happening (happened multiple times for me using the command: `wget --directory-prefix=../docker -nc --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1XkVpyYyYqQQ4FcgLIDUxg-GR1WI89-XC' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1XkVpyYyYqQQ4FcgLIDUxg-GR1WI89-XC" -O deployment_image.tar && rm -rf /tmp/cookies.txt
` in the file `go1_gym_deploy/scripts/send_to_unitree.sh`). 

One option is to download the file manually (stored [here](https://drive.google.com/file/d/1XkVpyYyYqQQ4FcgLIDUxg-GR1WI89-XC/view)) locally and then `scp` it to the robot in the same directory (replacing the corrupted file).

Don't forget to check the md5 checksum as shown [here](https://github.com/Improbable-AI/walk-these-ways/issues/42#issuecomment-1623976517).

**Comment by dongjukim123** [comment]
Thank you!
